add AllReviews and ReviewBox
Freeman-YFH/nc-games pull request #2
Opened 2023-04-17 15:21 UTC by Freeman-YFH

2023-04-17 15:26 UTC, popatre requested changes
Could you start setting up your Routes please?
And use your loading state to display some loading on the page? Just so we know something happening
Rest looks good

2023-04-17 15:26 UTC, popatre commented on src/App.js
> +      <AllReviews />
Could you set these up with routes/urls please? Presume this would be `/`

2023-04-17 15:26 UTC, popatre commented on src/components/AllReviews.jsx
> +                    return <ReviewBox key={review.review_id} {...review} />
nice components

2023-04-17 15:26 UTC, popatre commented on src/components/AllReviews.jsx
> +    const [isLoading, setIsLoading] = useState(true);
You've got your loading state that would done use.
COuld we get some feedback for when its loading on the page?

2023-04-18 09:14 UTC, itskatherine approved these changes
Nice addition of routes and loading states Freeman, good to merge 👍

2023-04-18 09:14 UTC, itskatherine commented on src/components/Login.jsx
> +            <Link to={'/allReviews'}>Reviews</Link>
Nice addition of routing

2023-04-18 09:17 UTC, merged